feature:
  - '/^\s*\[(feat|feature)\]/i'
  - '/^\s*(feat|feature)\s*[:\-]/i'

bug:
  - '/^\s*\[(fix|bug|hotfix)\]/i'
  - '/^\s*(fix|bug|hotfix)\s*[:\-]/i'

improvement:
  - '/^\s*\[(impr|improvement|perf|opt(?:imize|imization)?|usability)\]/i'
  - '/^\s*(impr|improvement|perf|opt(?:imize|imization)?|usability)\s*[:\-]/i'

refactoring:
  - '/^\s*\[(refactor|refactoring)\]/i'
  - '/^\s*(refactor|refactoring)\s*[:\-]/i'

documentation:
  - '/^\s*\[(docs?|documentation)\]/i'
  - '/^\s*(docs?|documentation)\s*[:\-]/i'
