feature:
  - '/^[\s\u200B]*[\[\uFF3B]\s*(?:feat|feature)\s*[\]\uFF3D]/iu'
  - '/^[\s\u200B]*(?:feat|feature)\s*[:\-\uFF1A]/iu'

bug:
  - '/^[\s\u200B]*[\[\uFF3B]\s*(?:fix|bug|hotfix)\s*[\]\uFF3D]/iu'
  - '/^[\s\u200B]*(?:fix|bug|hotfix)\s*[:\-\uFF1A]/iu'


improvement:
  - '/^[\s\u200B]*[\[\uFF3B]\s*(?:impr|improvement|perf)\s*[\]\uFF3D]/iu'
  - '/^[\s\u200B]*(?:impr|improvement|perf)\s*[:\-\uFF1A]/iu'

refactoring:
  - '/^[\s\u200B]*[\[\uFF3B]\s*(?:refactor|refactoring)\s*[\]\uFF3D]/iu'
  - '/^[\s\u200B]*(?:refactor|refactoring)\s*[:\-\uFF1A]/iu'

documentation:
  - '/^[\s\u200B]*[\[\uFF3B]\s*(?:docs?|documentation)\s*[\]\uFF3D]/iu'
  - '/^[\s\u200B]*(?:docs?|documentation)\s*[:\-\uFF1A]/iu'
