enable:
  issues: false

labels:
  'bug':
    include:
      - '/^[\s\u200B]*[\[\uFF3B]\s*(?:fix|bug|hotfix)\s*[\]\uFF3D]/iu'
      - '/^[\s\u200B]*(?:fix|bug|hotfix)\s*[:\-\uFF1A]/iu'
  'test':
    include:
      - '\btest\b'
  'feature':
    include:
      - '/^\s*\[\s*feature\s*\]/i'
      - '/^\s*(?:feat|feature)\s*[:\-]/i'
  'improvement':
    include:
      - '/^[\s\u200B]*[\[\uFF3B]\s*(?:impr|improvement|perf)\s*[\]\uFF3D]/iu'
      - '/^[\s\u200B]*(?:impr|improvement|perf)\s*[:\-\uFF1A]/iu'
  'refactoring':
    include:
      - '/^[\s\u200B]*[\[\uFF3B]\s*(?:refactor|refactoring)\s*[\]\uFF3D]/iu'
      - '/^[\s\u200B]*(?:refactor|refactoring)\s*[:\-\uFF1A]/iu'
  'documentation':
    include:
      - '/^[\s\u200B]*[\[\uFF3B]\s*(?:docs?|documentation)\s*[\]\uFF3D]/iu'
      - '/^[\s\u200B]*(?:docs?|documentation)\s*[:\-\uFF1A]/iu'
