enable:
  issues: true

labels:
  'bug':
    include:
      - '\bfix\b'
  'feature':
    include:
      - '\bfeat\b'
  'improvement':
    include:
      - '\bimprovement\b'
  'refactoring':
    include:
      - '\brefactor\b'
  'documentation':
    include:
      - '\bdocs\b'
