enable:
  issues: true

labels:
  'bug':
    include:
      - '(?i)^\s*(?:\[\s*(?:fix|bug|hotfix)\s*\]|(?:fix|bug|hotfix)\s*[:\-])'
  'feature':
    include:
      - '(?i)^\s*(?:\[\s*feature\s*\]|(?:feat|feature)\s*[:\-])'
  'improvement':
    include:
      - '(?i)^\s*(?:\[\s*(?:impr|improvement|perf)\s*\]|(?:impr|improvement|perf)\s*[:\-])'
  'refactoring':
    include:
      - '(?i)^\s*(?:\[\s*(?:refactor|refactoring)\s*\]|(?:refactor|refactoring)\s*[:\-])'
  'documentation':
    include:
      - '(?i)^\s*(?:\[\s*(?:docs?|documentation)\s*\]|(?:docs?|documentation)\s*[:\-])'
