name: Issue Labeler
on:
  issues:
    types: [opened, edited, reopened]

permissions:
  issues: write
  contents: read 

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/issue-labeler.yml
          include-title: true
          include-body: true
          enable-versioned-regex: true
