name: Issue Labeler

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read 
    
    steps:
      - name: Checkout dev branch and checkout labels
      -  id: labeler
      - uses: jimschubert/labeler-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ref: dev
          configuration-path: .github/labeler.yml
