name: Issue Labeler
on:
  issues:
    types: [opened, edited, reopened]

permissions:
  contents: read
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      # ↓ 디버그 스텝 1: 제목/본문 출력
      - name: Print issue title/body
        run: |
          echo "TITLE: ${{ github.event.issue.title }}"
          echo "BODY LENGTH: $(echo "${{ github.event.issue.body }}" | wc -c)"

      # ↓ 디버그 스텝 2: 정규식 매칭 드라이런
      - name: Dry-run match check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = context.payload.issue.title || "";
            const tests = [
              {name:"feature-1", re:/^\s*\[(feat|feature)\]/i},
              {name:"feature-2", re:/^\s*(feat|feature)\s*[:\-]/i},
              {name:"bug-1",     re:/^\s*\[(fix|bug|hotfix)\]/i},
              {name:"bug-2",     re:/^\s*(fix|bug|hotfix)\s*[:\-]/i},
            ];
            for (const t of tests) core.info(`${t.name}: ${t.re.test(title)}`);

      # ↓ 실제 라벨링 실행
      - uses: github/issue-labeler@v3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/issue-labeler.yml
          include-title: true
          include-body: true
          enable-versioned-regex: true
