name: Issue Labeler

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Run labeler
        id: labeler
        uses: jimschubert/labeler-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
