name: Release Drafter

on:
  push:
    branches:
      - dev
    issues:
      types: [opened, edited]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  issue_auto_label:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3
        with:
          configuration-path: .github/labeler.yml
          include-title: 1
          sync-labels: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}